<a href="https://colab.research.google.com/github/suryanshasayth936-ux/Python_Classes/blob/main/Class_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#numpy

import numpy as np

In [4]:
a = np.array([1,3,9,0,2])
print(a)
#prints array a above
b = np.array([1,3,9,0,'2'])
print(b)
#prints array b above, converts all data to string

[1 3 9 0 2]
['1' '3' '9' '0' '2']


In [9]:
np_arr = np.array([3,3,3,3,3.3,'hello',False])
print(bool(np_arr[-1]))


True


In [27]:
#Functions of NumPy
#zeroes and ones and full

a = np.ones((3,2,4), dtype=int)
print(a)
print(type(a[0][0][0]))

b = np.zeros((3,2,4), dtype=int)
print(b)
print(type(b[0][0][0]))

c = np.full((3,2,4),23,  dtype=int)
print(c)
print(type(c[0][0][0]))

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]
<class 'numpy.int64'>
[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>
[[[23 23 23 23]
  [23 23 23 23]]

 [[23 23 23 23]
  [23 23 23 23]]

 [[23 23 23 23]
  [23 23 23 23]]]
<class 'numpy.int64'>


In [40]:
#arange and linspace
a = np.arange(3,12,4)
print(a)
b = np.linspace(3,12,6, dtype = int)
print(b)

[ 3  7 11]
[ 3  4  6  8 10 12]


In [45]:
z = np.zeros((3,6), dtype = int)
print(np.shape(z))
print(np.size(z))

(3, 6)
18


In [60]:
#random integer and random choice

k = np.array([1,5,3,8,9])
print(np.random.randint(k)) #ye kaise run kr rha
print(np.random.choice(k)) #ye kaise run kr rha

print(np.random.randint(1,7,4))
print(np.random.choice([3,9,10,5,34,98,1], 2))

[0 1 0 1 6]
9
[2 4 4 5]
[ 5 10]


In [66]:
a = np.array(np.random.randint(1,10,6))
b = np.array(np.random.randint(10,20,6))
#BroadCasting in Matrices or Arrays
print(a)
print(a*2)
print(a+b)
print(b)
#Concatenation in Lists
l = [1,2,4,77]
print(l*2)
o = [7,0,6,91]
print(l+o)

[1 3 5 6 5 4]
[ 2  6 10 12 10  8]
[17 21 16 25 22 14]
[16 18 11 19 17 10]
[1, 2, 4, 77, 1, 2, 4, 77]
[1, 2, 4, 77, 7, 0, 6, 91]


In [71]:
#concatenate
#transpose

a = np.array(np.random.randint(3,10))
print(np.transpose(a))
axis

3


In [72]:
#where

a = np.random.randint(2,15,6)
b = np.random.randint(1,19,6)

c = np.where(b>2, b ,a)
print(c)

[ 4 15 17  8  7 14]


In [75]:
#sort, min, max
a = np.array(np.random.randint())

TypeError: randint() takes at least 1 positional argument (0 given)

In [ ]:
#Matric Multiply - MatMul


In [80]:
lst =[]
a = np.array(int(input()))
print(np.sum(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

100
100
0.0
100
100


In [81]:
a = np.array([3,3,3,3])
b =a
b[0] = 1
print(a,b)

[1 3 3 3] [1 3 3 3]
